In [1]:
import tensorflow as tf
print(tf.__version__)

2.1.0


In [2]:
import numpy as np

### tf.constant()

In [27]:
# 创建标量
# Constant 1-D Tensor populated with value list.
tensor_1 = tf.constant([1, 2, 3, 4, 5, 6])

tf.print(tensor_1)


# Constant 1-D Tensor populated with value list.
tensor_2 = tf.constant([1, 2, 3, 4, 5, 6], shape=(2,3))
print(tensor_2.numpy)


# Constant 2-D tensor populated with scalar value -1.
tensor_3 = tf.constant(-1.0, shape=[2, 3])
tensor_3.shape

[1 2 3 4 5 6]
<bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>>


TensorShape([2, 3])

In [41]:
# bool
true = tf.constant(True)
tf.print(true)
tf.print(true == True)

1
1


In [42]:
# 数值精度
tf.constant(123456789, dtype=tf.int32)

<tf.Tensor: shape=(), dtype=int32, numpy=123456789>

In [49]:
# 对于大部分深度学习算法，一般使用tf.int32, tf.float32 可满足运算精度要求
a = tf.constant(np.pi,dtype=tf.float32)

<tf.Tensor: shape=(), dtype=float32, numpy=3.1415927>

### tf.cast()

In [4]:
a = tf.constant(np.pi,dtype=tf.float32)
a

<tf.Tensor: shape=(), dtype=float32, numpy=3.1415927>

In [6]:
a_cast = tf.cast(a,tf.float64)
a_cast

<tf.Tensor: shape=(), dtype=float64, numpy=3.1415927410125732>

In [7]:
tf.dtypes.cast(a_cast,tf.float16)

<tf.Tensor: shape=(), dtype=float16, numpy=3.14>

### tf.print()

In [15]:
tensor = tf.range(10)
tf.print(tensor, output_stream=sys.stderr)

[0 1 2 ... 7 8 9]


In [16]:
# 类似正常print函数
tf.print("tensors:", tensor, {2: tensor * 2}, output_stream=sys.stdout)

tensors: [0 1 2 ... 7 8 9] {2: [0 2 4 ... 14 16 18]}


In [14]:
tf.print(tensor, tensor, output_stream=sys.stderr, sep=',')

[0 1 2 ... 7 8 9],[0 1 2 ... 7 8 9]


### tf.range()

In [18]:
#  range(n) = range(0, n)  => [0,n)
start = 3
limit = 18
delta = 3
tf.range(start, limit, delta)  # [3, 6, 9, 12, 15]

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([ 3,  6,  9, 12, 15])>

In [19]:
start = 3
limit = 1
delta = -0.5
tf.range(start, limit, delta)  # [3, 2.5, 2, 1.5]

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([3. , 2.5, 2. , 1.5], dtype=float32)>

In [20]:
limit = 5
tf.range(limit)  # [0, 1, 2, 3, 4]

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([0, 1, 2, 3, 4])>

### tf.strings.lower()

In [29]:
tf.strings.lower('AAA')

<tf.Tensor: shape=(), dtype=string, numpy=b'aaa'>

In [30]:
str1 = tf.constant('AAA')
tf.strings.lower(str1)

<tf.Tensor: shape=(), dtype=string, numpy=b'aaa'>

### tf.Variable()

`
tf.Variable(
    initial_value=None, trainable=None, validate_shape=True, caching_device=None,
    name=None, variable_def=None, dtype=None, import_scope=None, constraint=None,
    synchronization=tf.VariableSynchronization.AUTO,
    aggregation=tf.compat.v1.VariableAggregation.NONE, shape=None
)
`

In [11]:
a = tf.constant([-1, 0, 1, 2])
a_var = tf.Variable(a)

In [12]:
a_var.name

'Variable:0'

In [13]:
a_var.trainable  # 设置为false则在计算图中不需要优化

True

In [14]:
a = tf.Variable([[1,2],[3,4]])

In [23]:
# change value
v = tf.Variable(1.)
tf.print(v)
v.assign(2.)
tf.print(v)
v.assign_add(2.)
tf.print(v)

1
2
4


### tf.matmul()

In [26]:
w = tf.Variable([[1.], [2.]])
w.shape

TensorShape([2, 1])

In [27]:
x = tf.constant([[3., 4.]]) 
x.shape

TensorShape([1, 2])

In [28]:
# 矩阵相乘
tf.matmul(w, x)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[3., 4.],
       [6., 8.]], dtype=float32)>

In [29]:
tf.linalg.matmul(w,x)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[3., 4.],
       [6., 8.]], dtype=float32)>

### tf.Module()

In [60]:
# a named container 
m = tf.Module() 
m.a = tf.Variable([1.],name = 'a') 
m.b = tf.Variable(2,trainable=False,name = 'b')  # model可以保存trainable
m.trainable_variables

(<tf.Variable 'a:0' shape=(1,) dtype=float32, numpy=array([1.], dtype=float32)>,)

In [61]:
m.variables

(<tf.Variable 'a:0' shape=(1,) dtype=float32, numpy=array([1.], dtype=float32)>,
 <tf.Variable 'b:0' shape=() dtype=int32, numpy=2>)

In [77]:
m_sub = tf.Module(name='sub_module')
m_sub.v = tf.Variable('1-1',name='sub_v')
m.sub = m_sub
list(m.submodules) ==[m_sub]

True

In [78]:
m.submodules[0].variables

(<tf.Variable 'sub_v:0' shape=() dtype=string, numpy=b'1-1'>,)

### tf.function()  TODO

In [85]:
#在 TensorFlow 2.0 中，默认情况下，Eager Execution 处于启用状态。
# 这为您提供一个非常直观灵活的界面，
# 可以提升运行一次性操作的简易性和速度，但会降低性能和可部署性。

@tf.function
def f(): 
    return x ** 2 + y 
x = tf.constant([-2, -3]) 
y = tf.Variable([3, -2]) 
f()  # 已经在数据流图中了，所以可以不用进行传参

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 7])>

### tf.convert_to_tensor()

In [87]:
tf.constant([1,2])

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2])>

In [88]:
tf.Variable([1,2])

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([1, 2])>

In [86]:
tf.convert_to_tensor([1,2])

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2])>

### tf.zeros() & tf.ones()

In [90]:
tf.zeros([])

<tf.Tensor: shape=(), dtype=float32, numpy=0.0>

In [91]:
tf.zeros([1,2])

<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[0., 0.]], dtype=float32)>

In [92]:
tf.ones([1,2])

<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[1., 1.]], dtype=float32)>

### tf.zeros_like() & tf.ones_like()

In [94]:
a = tf.constant([1,2])

In [95]:
tf.zeros_like(a) 

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([0, 0])>

In [96]:
tf.ones_like(a) 

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 1])>

### tf.fill()

In [7]:
a =  tf.fill([],-1)
a

<tf.Tensor: shape=(), dtype=int32, numpy=-1>

In [8]:
tf.print(a)

-1


In [5]:
tf.fill([3,3],100)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[100, 100, 100],
       [100, 100, 100],
       [100, 100, 100]])>

### tf.random.normal()

In [10]:
# 归一化
tf.random.normal([2,2],seed = 123)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 2.4435377,  0.6532978],
       [-2.0876322, -0.6465399]], dtype=float32)>

In [58]:
# 应该是重新又new了对象
tf.random.normal([2,2],seed = 123)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.8412712 ,  0.01626102],
       [ 0.20710197,  0.07284655]], dtype=float32)>

In [55]:
tf.random.set_seed(222)
tf.random.normal([2,2])  

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 1.8662778, -1.7805147],
       [ 1.3079982, -1.4673755]], dtype=float32)>

In [96]:
tf.random.set_seed(222)   # 只要是重新set之后，对应顺序都相同
tf.random.normal([2,2])

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 1.8662778, -1.7805147],
       [ 1.3079982, -1.4673755]], dtype=float32)>

In [20]:
tf.random.normal([2,2], mean=1,stddev=2)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.7961674 , -2.6518288 ],
       [ 0.11116385, -1.9765894 ]], dtype=float32)>

### tf.random.uniform()

In [73]:
#可以创建采样自[𝑚𝑖𝑛𝑣𝑎𝑙, 𝑚𝑎𝑥𝑣𝑎𝑙]区间的均匀分布的张量。默认[0,1)
tf.random.uniform([2,2])

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.88968754, 0.12354946],
       [0.7718717 , 0.6850728 ]], dtype=float32)>

In [74]:
tf.random.uniform([2,2],minval=10,maxval=20)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[14.896269 , 15.8579235],
       [13.64517  , 16.550508 ]], dtype=float32)>

In [84]:
tf.random.set_seed(5) 
tf.random.uniform(shape=[], maxval=3, dtype=tf.int32, seed=10) 

<tf.Tensor: shape=(), dtype=int32, numpy=2>

### tf.one_hot()

In [104]:
tf.one_hot([2,3,0,1,2,1,1], depth=4) # one-hot 编码

<tf.Tensor: shape=(7, 4), dtype=float32, numpy=
array([[0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.]], dtype=float32)>

In [105]:
tf.one_hot([2,3,0,1,2,1,1], depth=4,axis=0) # axis =0 列

<tf.Tensor: shape=(4, 7), dtype=float32, numpy=
array([[0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 1., 1.],
       [1., 0., 0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.]], dtype=float32)>

In [106]:
tf.one_hot([2,3,0,1,2,1,1], depth=4,axis=1) # axis =1 行

<tf.Tensor: shape=(7, 4), dtype=float32, numpy=
array([[0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.]], dtype=float32)>

In [103]:
tf.one_hot([2,3,0,1], depth=4,on_value=10,off_value=-10) # one-hot 编码

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[-10, -10,  10, -10],
       [-10, -10, -10,  10],
       [ 10, -10, -10, -10],
       [-10,  10, -10, -10]])>

### tf.reduce_mean（）

In [114]:
tf.math.reduce_mean([1,2,3,4,5,6,7])

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [116]:
tf.math.reduce_mean([[1,3],[1,3]],axis=0)  # 按列

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 3])>

In [118]:
tf.math.reduce_mean([[1,3],[1,3]],axis=1)  # 按行

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 2])>

In [119]:
tf.math.reduce_mean([[1,3],[1,3]],axis=-1)  # 按行

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 2])>

In [15]:
tf.math.reduce_mean([[1,3],[1,3]])# 取平均

<tf.Tensor: shape=(), dtype=int32, numpy=2>

### 索引  & 切片

In [61]:
x = tf.random.normal([4,2,2,3])  # 如果是 [4,32,32,3]
x[0] # 2,2,3 = 2*(2,3)  取第一张图片

<tf.Tensor: shape=(2, 2, 3), dtype=float32, numpy=
array([[[-0.0366645 , -0.43328294, -1.1865592 ],
        [-0.5849128 , -0.92324436, -0.7670073 ]],

       [[-0.28764006, -1.3555579 ,  0.7478939 ],
        [ 0.58596945,  1.2730417 ,  0.088311  ]]], dtype=float32)>

In [62]:
x[0][1]  #  取第一张图片第一行

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[-0.28764006, -1.3555579 ,  0.7478939 ],
       [ 0.58596945,  1.2730417 ,  0.088311  ]], dtype=float32)>

In [64]:
x[0][1][1]   #  取第一张图片第一行第二列

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([0.58596945, 1.2730417 , 0.088311  ], dtype=float32)>

In [65]:
x[0][1][1][2] #  取第一张图片第一行第二列第三通道

<tf.Tensor: shape=(), dtype=float32, numpy=0.088311>

In [66]:
x[0,1,1,2]   

<tf.Tensor: shape=(), dtype=float32, numpy=0.088311>

In [68]:
x[0,1,1][:2]

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([0.58596945, 1.2730417 ], dtype=float32)>

In [69]:
x[:1,...,:2]

<tf.Tensor: shape=(1, 2, 2, 2), dtype=float32, numpy=
array([[[[-0.0366645 , -0.43328294],
         [-0.5849128 , -0.92324436]],

        [[-0.28764006, -1.3555579 ],
         [ 0.58596945,  1.2730417 ]]]], dtype=float32)>

In [70]:
x[:1,...]

<tf.Tensor: shape=(1, 2, 2, 3), dtype=float32, numpy=
array([[[[-0.0366645 , -0.43328294, -1.1865592 ],
         [-0.5849128 , -0.92324436, -0.7670073 ]],

        [[-0.28764006, -1.3555579 ,  0.7478939 ],
         [ 0.58596945,  1.2730417 ,  0.088311  ]]]], dtype=float32)>

### tf.reshape()

In [74]:
x=tf.range(96)
x = tf.reshape(x,[2,4,4,3])  # 改变视图
x

<tf.Tensor: shape=(2, 4, 4, 3), dtype=int32, numpy=
array([[[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11]],

        [[12, 13, 14],
         [15, 16, 17],
         [18, 19, 20],
         [21, 22, 23]],

        [[24, 25, 26],
         [27, 28, 29],
         [30, 31, 32],
         [33, 34, 35]],

        [[36, 37, 38],
         [39, 40, 41],
         [42, 43, 44],
         [45, 46, 47]]],


       [[[48, 49, 50],
         [51, 52, 53],
         [54, 55, 56],
         [57, 58, 59]],

        [[60, 61, 62],
         [63, 64, 65],
         [66, 67, 68],
         [69, 70, 71]],

        [[72, 73, 74],
         [75, 76, 77],
         [78, 79, 80],
         [81, 82, 83]],

        [[84, 85, 86],
         [87, 88, 89],
         [90, 91, 92],
         [93, 94, 95]]]])>

In [75]:
x.ndim

4

In [77]:
x = tf.reshape(x,[4,-1])
x.shape

TensorShape([4, 24])

###  tf.expand_dims()

In [97]:
x = tf.random.uniform([3,3],maxval=10,dtype=tf.int32)

In [98]:
tf.expand_dims(x,axis=2)  # 在指定的axis 轴前可以插入一个新的维度  3 *(3,1)

<tf.Tensor: shape=(3, 3, 1), dtype=int32, numpy=
array([[[9],
        [3],
        [9]],

       [[8],
        [3],
        [2]],

       [[3],
        [7],
        [9]]])>

In [100]:
tf.expand_dims(x,axis=1)  # 3 *(3,1)

<tf.Tensor: shape=(3, 1, 3), dtype=int32, numpy=
array([[[9, 3, 9]],

       [[8, 3, 2]],

       [[3, 7, 9]]])>

In [101]:
tf.expand_dims(x, -1)

<tf.Tensor: shape=(3, 3, 1), dtype=int32, numpy=
array([[[9],
        [3],
        [9]],

       [[8],
        [3],
        [2]],

       [[3],
        [7],
        [9]]])>

### tf.squeeze()

In [116]:
x = tf.random.uniform([1,3,3,1],maxval=10,dtype=tf.int32)  
x

<tf.Tensor: shape=(1, 3, 3, 1), dtype=int32, numpy=
array([[[[1],
         [8],
         [4]],

        [[9],
         [2],
         [7]],

        [[4],
         [7],
         [8]]]])>

In [117]:
tf.squeeze(x, axis=0)# 注意这里只能删除长度为1 的维度

<tf.Tensor: shape=(3, 3, 1), dtype=int32, numpy=
array([[[1],
        [8],
        [4]],

       [[9],
        [2],
        [7]],

       [[4],
        [7],
        [8]]])>

In [118]:
tf.squeeze(x)  # 删除所有维度为1的维度

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 8, 4],
       [9, 2, 7],
       [4, 7, 8]])>

###  tf.transpose()

In [126]:
# 改变视图、增删维度都不会影响张量的存储。但交换维度，会改变张量的存储顺序，同时也改变张量的视图。
x = tf.random.normal([2,32,32,3])

In [127]:
# 应用：通道后行改为通道先行
x_new = tf.transpose(x,perm=[0,3,1,2])  # 后续的所有操作必须基于新的存储顺序进行。
x_new.shape

TensorShape([2, 3, 32, 32])

In [129]:
x = tf.constant([[1 + 1j, 2 + 2j, 3 + 3j],
                 [4 + 4j, 5 + 5j, 6 + 6j]])
tf.transpose(x, conjugate=True)  # 共轭

<tf.Tensor: shape=(3, 2), dtype=complex128, numpy=
array([[1.-1.j, 4.-4.j],
       [2.-2.j, 5.-5.j],
       [3.-3.j, 6.-6.j]])>

### tf.keras.preprocessing.sequence.pad_sequences()

In [43]:
#  return ：Numpy array with shape `(len(sequences), maxlen)`
sequences = [[1,2,3],[2,1,1]]

In [44]:
tf.keras.preprocessing.sequence.pad_sequences(sequences,10)

array([[0, 0, 0, 0, 0, 0, 0, 1, 2, 3],
       [0, 0, 0, 0, 0, 0, 0, 2, 1, 1]])

In [46]:
# padding：‘pre’或‘post’，确定当需要补0时，在序列的起始还是结尾补
# value：浮点数，此值将在填充时代替默认的填充值0
tf.keras.preprocessing.sequence.pad_sequences(sequences,10,padding= 'post',value = 5)

array([[1, 2, 3, 5, 5, 5, 5, 5, 5, 5],
       [2, 1, 1, 5, 5, 5, 5, 5, 5, 5]])

In [47]:
# truncating：‘pre’或‘post’，确定当需要截断序列时，从起始还是结尾截断
tf.keras.preprocessing.sequence.pad_sequences(sequences,2,truncating= 'post')

array([[1, 2],
       [2, 1]])

### tf.keras.layers.Dense()

In [13]:
# tf.keras.layers.Dense(
#     units, activation=None, use_bias=True, kernel_initializer='glorot_uniform',
#     bias_initializer='zeros', kernel_regularizer=None, bias_regularizer=None,
#     activity_regularizer=None, kernel_constraint=None, bias_constraint=None,
#     **kwargs
# )

In [20]:
fc = tf.keras.layers.Dense(3)  # 输出维度为3
fc.build((2,4)) # Creates the variables of the layer  输入结点为4  
fc.bias

<tf.Variable 'bias:0' shape=(3,) dtype=float32, numpy=array([0., 0., 0.], dtype=float32)>

In [22]:
fc.kernel

<tf.Variable 'kernel:0' shape=(4, 3) dtype=float32, numpy=
array([[ 0.07445002, -0.5755564 , -0.1395914 ],
       [-0.8084033 ,  0.5287454 ,  0.88331604],
       [-0.36245656,  0.07084394, -0.266676  ],
       [ 0.663033  , -0.5536047 , -0.26633167]], dtype=float32)>

In [21]:
# 等价于
x = tf.random.normal([2,4])
w = tf.ones([4,3]) # 定义W 张量
b = tf.zeros([3]) # 定义b 张量
o = x@w+b # X@W+b 运算  矩阵乘法
o

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[-0.76846385, -0.76846385, -0.76846385],
       [-3.8085492 , -3.8085492 , -3.8085492 ]], dtype=float32)>

### tf.keras.layers.Embedding()

In [40]:
# 加载IMDB 电影评价数据集
(x_train,y_train),(x_test,y_test)=tf.keras.datasets.imdb.load_data(path = r'E:\研究生自学\深度框架学习\my-tensorflow-study\all-basic\dataset\imdb\imdb.npz',num_words=10000)
x_train[:2]

array([list([1, 14, 22, 16, 43, 530, 973, 1622, 1385, 65, 458, 4468, 66, 3941, 4, 173, 36, 256, 5, 25, 100, 43, 838, 112, 50, 670, 2, 9, 35, 480, 284, 5, 150, 4, 172, 112, 167, 2, 336, 385, 39, 4, 172, 4536, 1111, 17, 546, 38, 13, 447, 4, 192, 50, 16, 6, 147, 2025, 19, 14, 22, 4, 1920, 4613, 469, 4, 22, 71, 87, 12, 16, 43, 530, 38, 76, 15, 13, 1247, 4, 22, 17, 515, 17, 12, 16, 626, 18, 2, 5, 62, 386, 12, 8, 316, 8, 106, 5, 4, 2223, 5244, 16, 480, 66, 3785, 33, 4, 130, 12, 16, 38, 619, 5, 25, 124, 51, 36, 135, 48, 25, 1415, 33, 6, 22, 12, 215, 28, 77, 52, 5, 14, 407, 16, 82, 2, 8, 4, 107, 117, 5952, 15, 256, 4, 2, 7, 3766, 5, 723, 36, 71, 43, 530, 476, 26, 400, 317, 46, 7, 4, 2, 1029, 13, 104, 88, 4, 381, 15, 297, 98, 32, 2071, 56, 26, 141, 6, 194, 7486, 18, 4, 226, 22, 21, 134, 476, 26, 480, 5, 144, 30, 5535, 18, 51, 36, 28, 224, 92, 25, 104, 4, 226, 65, 16, 38, 1334, 88, 12, 16, 283, 5, 16, 4472, 113, 103, 32, 15, 16, 5345, 19, 178, 32]),
       list([1, 194, 1153, 194, 8255, 78, 228,

In [41]:
# 将句子填充、截断为等长80 个单词的句子
x_train = tf.keras.preprocessing.sequence.pad_sequences(x_train,maxlen=80)
x_train

array([[  15,  256,    4, ...,   19,  178,   32],
       [ 125,   68,    2, ...,   16,  145,   95],
       [ 645,  662,    8, ...,    7,  129,  113],
       ...,
       [ 529,  443,    2, ...,    4, 3586,    2],
       [ 286, 1814,   23, ...,   12,    9,   23],
       [  97,   90,   35, ...,  204,  131,    9]])

In [42]:
x_train.shape

(25000, 80)

In [50]:
# 创建词向量Embedding 层类
embedding=tf.keras.layers.Embedding(10000, 100)

In [51]:
# 将数字编码的单词转换为词向量
# 其中100 表示每个单词编码为长度100 的向量。
# 输入形状 二维张量(batch_size,input_length)
# 输出形状 三维张量(batch_size,input_length,output_dim)
out = embedding(x_train)
out.shape

TensorShape([25000, 80, 100])

### tf.keras.layers.conv2D()

In [54]:
# 输入 channel_last:(samples, new_rows, new_cols, filters)
x = tf.random.normal([4,32,32,3])  # [batch,h,w,3]
layer = tf.keras.layers.Conv2D(16,kernel_size=3)

In [56]:
# 输出 channel_last:(samples, new_rows, new_cols, filters) 
out = layer(x) # 前向计算
out.shape # 输出大小

TensorShape([4, 30, 30, 16])

In [57]:
# 卷积核
layer.kernel.shape

TensorShape([3, 3, 3, 16])

### demo-1

In [125]:
out = tf.random.uniform([4,10]) #随机模拟网络输出
y = tf.constant([2,3,2,0]) # 随机构造样本真实标签
y = tf.one_hot(y, depth=10) # one-hot 编码
loss = tf.keras.losses.mse(y, out) # 计算每个样本的MSE
loss = tf.math.reduce_mean(loss) # 平均MSE
print(loss)

tf.Tensor(0.3461089, shape=(), dtype=float32)
